import { DESIGN_HEIGHT, DESIGN_WIDTH, STORAGE_KEYS } from "./config.js";
import { AudioManager } from "./AudioManager.js";
import { buildVisualAssets } from "./AssetFactory.js";
import { SceneManager } from "./SceneManager.js";
import { GameOverScene, GameplayScene, MenuScene } from "./scenes.js";
export class Game { constructor(root){ this.root=root; this.app=new PIXI.Application({width:DESIGN_WIDTH,height:DESIGN_HEIGHT,backgroundColor:0x000000,antialias:true,autoDensity:true,resolution:Math.min(window.devicePixelRatio||1,2),forceCanvas:false}); this.stage=this.app.stage; this.input={left:0,right:0}; this.bestScore=Number(localStorage.getItem(STORAGE_KEYS.bestScore)||0); this.audio=new AudioManager(); this.scenes=new SceneManager(this); this.app.view.tabIndex=0; this.app.view.setAttribute("aria-label","peixe inteligente game canvas"); this.root.appendChild(this.app.view); this.bindInput(); this.app.ticker.add(()=>{ const dt=Math.min(0.05,this.app.ticker.elapsedMS/1000); this.scenes.update(dt); }); }
async init(){ this.visuals=await buildVisualAssets(); await this.scenes.set(MenuScene); }
bindInput(){ window.addEventListener("keydown",e=>{ if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a"){e.preventDefault();this.input.left=1;} if(e.key==="ArrowRight"||e.key.toLowerCase()==="d"){e.preventDefault();this.input.right=1;} if(e.key==="Enter"||e.key===" ")e.preventDefault(); }); window.addEventListener("keyup",e=>{ if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")this.input.left=0; if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")this.input.right=0; }); this.app.view.addEventListener("pointerdown",async e=>{ await this.audio.unlock(); const rect=this.app.view.getBoundingClientRect(); const x=e.clientX-rect.left; this.input.left=x<rect.width*0.5?1:0; this.input.right=x>=rect.width*0.5?1:0; this.app.view.focus(); }); window.addEventListener("pointerup",()=>{this.input.left=0;this.input.right=0;}); }
startRun(){ this.input.left=0; this.input.right=0; this.scenes.set(GameplayScene); }
endRun(score){ const finalScore=Math.floor(score); this.bestScore=Math.max(this.bestScore,finalScore); localStorage.setItem(STORAGE_KEYS.bestScore,String(this.bestScore)); this.scenes.set(GameOverScene,{score:finalScore}); } }
