import { CleanBackground } from "./Background.js";
import { Oil } from "./Oil.js";
import { ParticleSystem } from "./ParticleSystem.js";
import { Player } from "./Player.js";
import { Hud, makeButton, makeControlsHint, makeSoundToggle, makeText } from "./UI.js";
import { clamp, lerp, padScore, rand } from "./utils.js";
class BaseScene { constructor(game,mode="play"){ this.game=game; this.container=new PIXI.Container(); this.elapsed=0; this.bg=new CleanBackground(mode); this.container.addChild(this.bg.container); } update(dt){ this.elapsed+=dt; this.bg.update(dt,this.scrollSpeed||0); } destroy(){ this.container.destroy({children:true}); } }
export class MenuScene extends BaseScene { constructor(game){ super(game,"menu"); const title=makeText("peixe\ninteligente",150,"left"); title.position.set(135,185); title.style.fontWeight="700"; const sub=makeText("out of the oil",42,"left"); sub.position.set(1335,646); this.hero=new PIXI.Sprite(game.visuals.fishHero); this.hero.anchor.set(0.5); this.hero.position.set(1180,548); this.hero.scale.set(1.95); this.start=makeButton("CLICK TO START",324,64,async()=>{ await this.game.audio.unlock(); this.game.startRun(); }); this.start.position.set(960,827); this.soundToggle=makeSoundToggle(this.game.audio); this.hint=makeControlsHint(); this.container.addChild(title,sub,this.hero,this.start,this.soundToggle,this.hint); }
async enter(){ await this.game.audio.warmStart(); }
update(dt){ super.update(dt); this.hero.rotation=Math.sin(this.elapsed*0.8)*0.035; this.hero.scale.set(1.95+Math.sin(this.elapsed*1.2)*0.025); this.game.audio.update(dt,this.elapsed,"menu"); } }
export class GameplayScene extends BaseScene { constructor(game){ super(game,"play"); this.player=new Player(game.visuals.fish,game.visuals.skeleton); this.particles=new ParticleSystem(); this.oilContainer=new PIXI.Container(); this.hud=new Hud(game.bestScore); this.soundToggle=makeSoundToggle(this.game.audio); this.hint=makeControlsHint(); this.container.addChild(this.oilContainer,this.particles.container,this.player.container,this.hud.container,this.soundToggle,this.hint); this.score=0; this.spawnTimer=0.62; this.oils=[]; this.scrollSpeed=330; this.slowMo=1; this.crashed=false; this.crashTimer=0; this.previousInput=0; }
update(dt){ super.update(dt); const activeDt=dt*this.slowMo; this.scrollSpeed=340+420*(1-Math.exp(-this.elapsed/18)); this.score+=this.crashed?0:activeDt; this.spawnTimer-=activeDt; const input=this.game.input.right-this.game.input.left; this.player.setInput(input); if(input!==0&&input!==this.previousInput)this.game.audio.blip("move"); this.previousInput=input; this.player.update(activeDt,this.scrollSpeed/600); if(!this.crashed&&Math.random()<activeDt*8)this.particles.spawnBubbleTrail(this.player.x,this.player.y,1); if(!this.crashed&&this.spawnTimer<=0){ this.spawnOilWave(); this.spawnTimer=clamp(1.12-this.elapsed*0.022,0.34,1.12)+rand(0,0.22); } for(const oil of this.oils){ oil.update(activeDt,this.scrollSpeed,this.elapsed); if(!this.crashed&&oil.collides(this.player.getHitCircles()))this.handleCrash(oil); } for(let i=this.oils.length-1;i>=0;i--){ if(this.oils[i].dead){ this.oils[i].destroy(); this.oils.splice(i,1); } } this.particles.update(activeDt,this.scrollSpeed); this.hud.update(this.score,this.game.bestScore,this.elapsed); this.game.audio.update(dt,this.elapsed,"gameplay",this.slowMo); if(this.crashed){ this.crashTimer+=dt; this.slowMo=lerp(this.slowMo,0.18,dt*7); if(this.crashTimer>0.58)this.game.endRun(this.score); } }
spawnOilWave(){ const count=this.elapsed>18&&Math.random()<0.42?2:1; for(let i=0;i<count;i++){ const oil=Oil.randomSpawn(this.game.visuals.oils,this.elapsed+i*2); if(count===2)oil.container.x+=i===0?-260:260; this.oilContainer.addChild(oil.container); this.oils.push(oil); } }
handleCrash(oil){ this.crashed=true; this.crashTimer=0; this.player.kill(); this.particles.spawnSplash(this.player.x,this.player.y-30); oil.sprite.scale.x*=1.18; oil.sprite.scale.y*=1.1; this.game.audio.blip("oil"); }
destroy(){ this.player.destroy(); this.particles.destroy(); for(const oil of this.oils)oil.destroy(); super.destroy(); } }
export class GameOverScene extends BaseScene { constructor(game,data){ super(game,"over"); this.finalScore=data.score||0; const label=makeText("i.q score",58,"center"); label.anchor.set(0.5); label.position.set(960,320); const score=makeText(padScore(this.finalScore),84,"center"); score.anchor.set(0.5); score.position.set(960,430); const restart=makeButton("RESTART",210,64,async()=>{ await this.game.audio.unlock(); this.game.startRun(); }); restart.position.set(960,565); const skeleton=new PIXI.Sprite(game.visuals.skeleton); skeleton.anchor.set(0.5); skeleton.position.set(960,830); skeleton.scale.set(0.88); this.skeleton=skeleton; this.soundToggle=makeSoundToggle(this.game.audio); this.hint=makeControlsHint(); this.container.addChild(skeleton,label,score,restart,this.soundToggle,this.hint); }
update(dt){ super.update(dt); this.skeleton.rotation=Math.sin(this.elapsed*1.5)*0.08; this.skeleton.y=830+Math.sin(this.elapsed*1.8)*10; this.game.audio.update(dt,this.elapsed,"gameover",0.42); } }
